# Generated by Django 4.2.24 on 2025-09-07 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20250907_1506'),
    ]

    operations = [
    ]
