# Generated by Django 4.2.24 on 2025-09-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_review_uq_review_course_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name='Оплачено в',
            ),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt',
            field=models.FileField(
                upload_to='payments/receipts/',
                blank=True,
                null=True,
                verbose_name='Чек/квитанция',
            ),
        ),
        migrations.AddField(
            model_name='payment',
            name='verified_at',
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name='Проверено в',
            ),
        ),
    ]
