# Generated by Django 4.2.24 on 2025-10-27 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_article_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотры'),
        ),
        migrations.AlterField(
            model_name='material',
            name='download_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Скачивания'),
        ),
    ]
