# Generated by Django 4.2.24 on 2025-09-14 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_course_is_popular_lessonprogress'),
    ]

    operations = [
    ]
