# Generated by Django 4.2.24 on 2025-12-12 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_article_view_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='experience',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Опыт (лет)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.CharField(blank=True, max_length=100, verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, max_length=50, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='course_updates',
            field=models.BooleanField(default=True, verbose_name='Обновления курсов'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_notifications',
            field=models.BooleanField(default=True, verbose_name='Email уведомления'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='newsletter',
            field=models.BooleanField(default=False, verbose_name='Рассылка'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='position',
            field=models.CharField(blank=True, max_length=100, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='push_reminders',
            field=models.BooleanField(default=True, verbose_name='Напоминания'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='website',
            field=models.URLField(blank=True, verbose_name='Веб-сайт'),
        ),
    ]
