# Generated by Django 4.2.24 on 2025-12-13 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_instructorprofile_experience_userprofile_bio_and_more'),
    ]

    operations = [
    ]
