# Generated by Django 4.2.24 on 2025-09-22 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_payment_options_course_author_and_more'),
        ('app', '0007_remove_category_app_category_order_idx_and_more'),
    ]

    operations = [
    ]
