# Generated by Django 4.2.24 on 2025-12-14 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_course_status_alter_article_body'),
    ]

    operations = [
    ]
