# Generated by Django 4.2.24 on 2025-09-22 18:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_merge_20250922_2059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonprogress',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Прогресс по уроку', 'verbose_name_plural': 'Прогресс по урокам'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created'], 'verbose_name': 'Платеж', 'verbose_name_plural': 'Платежи'},
        ),
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='course',
            name='author',
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='percent',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='experience',
            field=models.PositiveIntegerField(default=0, verbose_name='Опыт работы (лет)'),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Подтвержден'),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='app.lesson'),
        ),
        migrations.AddConstraint(
            model_name='lessonprogress',
            constraint=models.UniqueConstraint(fields=('user', 'lesson'), name='uq_lessonprogress_user_lesson'),
        ),
        migrations.RemoveField(
            model_name='lessonprogress',
            name='completed_at',
        ),
    ]
