# Generated by Django 4.2.24 on 2025-09-29 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_add_excerpt_slug'),
        ('app', '0009_fix_material_slug_like_index'),
    ]

    operations = [
    ]
