# Generated by Django 4.2.24 on 2025-12-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_add_platform_role_to_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='platform_role',
            field=models.CharField(choices=[('student', 'Студент'), ('support', 'Поддержка'), ('content', 'Контент-менеджер'), ('platform_admin', 'Администратор платформы')], default='student', help_text='Глобальная роль на платформе', max_length=20, verbose_name='Платформенная роль'),
        ),
    ]
