# Generated by Django 4.2.24 on 2025-09-30 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_add_article_body_and_material_description'),
    ]

    operations = [
    ]
