# Generated by Django 4.2.24 on 2025-09-30 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_sync_with_supabase'),
    ]

    operations = [
    ]
