# Generated by Django 4.2.24 on 2025-09-30 23:57

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0014_sync_with_supabase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at', '-created_at'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Сообщение контактов', 'verbose_name_plural': 'Сообщения контактов'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['module__order', 'order', 'id'], 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AlterModelOptions(
            name='lessonprogress',
            options={'verbose_name': 'Прогресс по уроку', 'verbose_name_plural': 'Прогресс по урокам'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['-created_at'], 'verbose_name': 'Материал', 'verbose_name_plural': 'Материалы'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Модуль', 'verbose_name_plural': 'Модули'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Платёж', 'verbose_name_plural': 'Платежи'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.RemoveConstraint(
            model_name='enrollment',
            name='uq_enrollment_user_course',
        ),
        migrations.RemoveConstraint(
            model_name='lesson',
            name='uq_lesson_module_slug',
        ),
        migrations.RemoveConstraint(
            model_name='lessonprogress',
            name='uq_lessonprogress_user_lesson',
        ),
        migrations.RemoveConstraint(
            model_name='wishlist',
            name='uq_wishlist_user_course',
        ),
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='category',
            name='order',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='course',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_popular',
        ),
        migrations.RemoveField(
            model_name='course',
            name='language',
        ),
        migrations.RemoveField(
            model_name='course',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='course',
            name='status',
        ),
        migrations.RemoveField(
            model_name='course',
            name='what_you_learn',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='enrolled_at',
        ),
        migrations.RemoveField(
            model_name='instructorprofile',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='instructorprofile',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='instructorprofile',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='instructorprofile',
            name='website',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='created',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paid_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='verified_at',
        ),
        migrations.RemoveField(
            model_name='review',
            name='age',
        ),
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
        migrations.RemoveField(
            model_name='review',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='review',
            name='position',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='added_at',
        ),
        migrations.AddField(
            model_name='article',
            name='body',
            field=models.TextField(blank=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='article',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='Обложка'),
        ),
        migrations.AddField(
            model_name='article',
            name='seo_description',
            field=models.CharField(blank=True, max_length=500, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='article',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=500, verbose_name='SEO Keywords'),
        ),
        migrations.AddField(
            model_name='article',
            name='seo_schema',
            field=models.TextField(blank=True, verbose_name='SEO Schema (JSON-LD)'),
        ),
        migrations.AddField(
            model_name='article',
            name='seo_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AddField(
            model_name='material',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='material',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='materials/images/', verbose_name='Превью'),
        ),
        migrations.AddField(
            model_name='module',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано')], default='draft', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=160, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='app.category'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration_hours',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность (часы)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_courses', to=settings.AUTH_USER_MODEL, verbose_name='Инструктор'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='В подборке'),
        ),
        migrations.AlterField(
            model_name='course',
            name='short_description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Короткое описание'),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='enrolled_courses', through='app.Enrollment', to=settings.AUTH_USER_MODEL, verbose_name='Студенты'),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='courses/thumbs/', verbose_name='Превью'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Курс завершён'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='app.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='instructors/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='Профиль подтверждён'),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='specialization',
            field=models.CharField(blank=True, max_length=255, verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='instructorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность (мин.)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='app.module', verbose_name='Модуль'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название урока'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Завершён'),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='app.lesson', verbose_name='Урок'),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='percent',
            field=models.PositiveIntegerField(default=0, verbose_name='Прогресс, %'),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='material',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='materials/files/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='material',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Показывать на сайте'),
        ),
        migrations.AlterField(
            model_name='material',
            name='slug',
            field=models.SlugField(max_length=220, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='material',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='material',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='module',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='app.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='module',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='module',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='module',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название модуля'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='app.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='kaspi_invoice_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Kaspi invoice ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='payments/receipts/', verbose_name='Чек'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('success', 'Успешно'), ('failed', 'Ошибка')], default='pending', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='review',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='app.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Показывать'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Оценка (1–5)'),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_in', to='app.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('module', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('course', 'order')},
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['slug'], name='app_article_slug_f27594_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['slug'], name='app_course_slug_24512e_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['-created_at'], name='app_course_created_4cc70f_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['user', 'course'], name='app_enrollm_user_id_57c5bf_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['kaspi_invoice_id'], name='app_payment_kaspi_i_71e2ac_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'course'], name='app_payment_user_id_ab13a5_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['course'], name='app_review_course__20c9e5_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('user', 'course'), name='uniq_enrollment_user_course'),
        ),
        migrations.AddConstraint(
            model_name='lessonprogress',
            constraint=models.UniqueConstraint(fields=('user', 'lesson'), name='uniq_progress_user_lesson'),
        ),
        migrations.AddConstraint(
            model_name='wishlist',
            constraint=models.UniqueConstraint(fields=('user', 'course'), name='uniq_wishlist_user_course'),
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='content',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='is_free',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='resources',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='video_url',
        ),
        migrations.RemoveField(
            model_name='module',
            name='description',
        ),
    ]
