# Generated by Django 4.2.24 on 2025-10-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_squashed_0015_remove_subscription_user_alter_article_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(blank=True, default='Текст появится позже', verbose_name='Текст'),
        ),
    ]
